# Autogenerated wrapper script for CombBLAS_jll for aarch64-apple-darwin-cxx03-mpi+mpitrampoline
export libCombBLAS, libGraphGenlib

using CompilerSupportLibraries_jll
using MPItrampoline_jll
JLLWrappers.@generate_wrapper_header("CombBLAS")
JLLWrappers.@declare_library_product(libCombBLAS, "@rpath/libCombBLAS.1.16.0.dylib")
JLLWrappers.@declare_library_product(libGraphGenlib, "@rpath/libGraphGenlib.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libCombBLAS,
        "lib/libCombBLAS.1.16.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libGraphGenlib,
        "lib/libGraphGenlib.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
